name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 17 (using Temurin distribution)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install -Pproduction

      # Set up Google Cloud CLI
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: gcp-peoject-1

      # Authenticate to Google Cloud using service account
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SECONDPROJECT }}

      # Fetch DB Secrets from Google Secret Manager
      - name: Fetch DB Secrets from Google Secret Manager
        run: |
          DB_URL=$(gcloud secrets versions access latest --secret="DB_URL")
          DB_USERNAME=$(gcloud secrets versions access latest --secret="DB_USERNAME")
          DB_PASSWORD=$(gcloud secrets versions access latest --secret="DB_PASSWORD")
          
          # Debug: Print the values (you can remove these lines after validation)
          echo "DB_URL=$DB_URL"
          echo "DB_USERNAME=$DB_USERNAME"
          echo "DB_PASSWORD=$DB_PASSWORD"

      # Configure Docker to use gcloud credentials
      - name: Configure Docker to use gcloud credentials
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/gcp-peoject-1/second-repo/taskmob .

      # Push Docker Image to Artifact Registry
      - name: Push Docker Image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/gcp-peoject-1/second-repo/taskmob

      # Deploy to Google Cloud Run with DB details as environment variables from Secret Manager
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy second-service \
            --image us-central1-docker.pkg.dev/gcp-peoject-1/second-repo/taskmob \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --service-account second-repo@gcp-peoject-1.iam.gserviceaccount.com \
            --set-secrets SPRING_DATASOURCE_URL=projects/gcp-peoject-1/secrets/DB_URL:latest,SPRING_DATASOURCE_USERNAME=projects/gcp-peoject-1/secrets/DB_USERNAME:latest,SPRING_DATASOURCE_PASSWORD=projects/gcp-peoject-1/secrets/DB_PASSWORD:latest
